"""Swift source templates of the scaffold's contract layer (navigation, headless, gate).

Pure rendering: :mod:`iosforge.mvp.swiftui_scaffold` decides *what* to render
(screens, tabs, owners); this module only turns that plan into Swift. Every file
carries the "Generated by the IOSForge scaffold — do not edit." marker and is
restored byte-for-byte by the compile gate.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Literal

from iosforge.mvp.swiftui_permissions import PERMISSION_KINDS, PERMISSIONS_DIR

Presentation = Literal["onboarding", "tabRoot", "push", "sheet", "fullScreenCover"]

DO_NOT_EDIT = "Generated by the IOSForge scaffold — do not edit."
PENDING_MARKER = "PendingScreenView(id:"

_CONTROL = re.compile(r"[\x00-\x1f\x7f]+")
_SWIFT_ESCAPES = {"\\": "\\\\", '"': '\\"', "\n": "\\n", "\r": "\\r", "\t": "\\t"}


@dataclass(frozen=True)
class ScreenEntry:
    """One ``app_spec`` screen as the scaffold renders it."""

    screen_id: str
    name: str
    case_name: str
    type_name: str
    presentation: Presentation
    onboarding: bool
    tab_root: str | None = None
    shows_tab_bar: bool = False

    @property
    def view_path(self) -> str:
        """Model-owned view file of this screen, relative to the app directory."""
        return f"App/Features/{self.screen_id}/{self.type_name}.swift"

    @property
    def fixtures_path(self) -> str:
        """Model-owned fixtures file of this screen, relative to the app directory."""
        suffix = self.type_name.removeprefix("Screen").removesuffix("View")
        return f"App/Fixtures/Fixtures{suffix}.swift"


@dataclass(frozen=True)
class TabEntry:
    """One root tab as rendered into ``AppTab``."""

    case_name: str
    title: str
    root: ScreenEntry


def swift_str(value: str) -> str:
    """Swift string literal; control characters as ``\\u{..}`` (JSON's ``\\uXXXX`` is invalid)."""
    body = "".join(
        _SWIFT_ESCAPES.get(ch) or (f"\\u{{{ord(ch):x}}}" if ord(ch) < 0x20 else ch) for ch in value
    )
    return f'"{body}"'


def clean_text(value: str) -> str:
    """Single-line text safe inside a Swift ``//`` comment."""
    return _CONTROL.sub(" ", value).strip()


_LAUNCH_CONDITIONS = {
    "every_launch": "everyLaunch",
    "first_launch": "firstLaunch",
    "not_premium": "notPremium",
}


def render_screen_id(
    entries: list[ScreenEntry],
    tabs: list[TabEntry],
    launch: list[dict[str, str]] | None = None,
) -> str:
    """``ScreenID`` enum: cases, presentation, owning tab, view factory, launch screens."""
    by_id = {e.screen_id: e for e in entries}
    launch_rows = [
        f"        ScaffoldLaunchScreen(screen: .{by_id[item['screen_id']].case_name}, "
        f"asSheet: {'true' if item.get('presentation') == 'sheet' else 'false'}, "
        f"condition: .{_LAUNCH_CONDITIONS.get(item.get('condition', ''), 'everyLaunch')}),"
        for item in launch or []
        if item.get("screen_id") in by_id
    ]
    launch_block = (
        "\n\n    /// Screens presented over the app on start (`app_spec.navigation.launch`).\n"
        "    static let launchScreens: [ScaffoldLaunchScreen] = [\n"
        + "\n".join(launch_rows)
        + "\n    ]\n"
        if launch_rows
        else "\n"
    )
    launch_type = LAUNCH_TYPE if launch_rows else ""
    by_root = {t.root.screen_id: t for t in tabs}
    cases = "\n".join(
        f"    case {e.case_name} = {swift_str(e.screen_id)}  // {clean_text(e.name)}"
        for e in entries
    )
    presentations = "\n".join(f"        case .{e.case_name}: .{e.presentation}" for e in entries)
    owner_lines = []
    for e in entries:
        tab = by_root.get(e.tab_root) if e.tab_root else None
        owner_lines.append(
            f"        case .{e.case_name}: {('.' + tab.case_name) if tab else 'nil'}"
        )
    owners = "\n".join(owner_lines)
    views = "\n".join(f"        case .{e.case_name}: {e.type_name}()" for e in entries)
    bar_cases = [f".{e.case_name}" for e in entries if e.shows_tab_bar]
    bar_check = f"[{', '.join(bar_cases)}].contains(self)" if bar_cases else "false"
    onboarding = [e for e in entries if e.onboarding]
    first_onboarding = f".{onboarding[0].case_name}" if onboarding else "nil"
    return f"""import SwiftUI

/// Every screen of the app, keyed by its app_spec id (the `-screen-id` value).
/// {DO_NOT_EDIT}
enum ScreenID: String, CaseIterable, Identifiable, Hashable {{
{cases}

    var id: String {{ rawValue }}

    /// First onboarding screen for a normal (non-headless) first launch.
    static let onboardingStart: ScreenID? = {first_onboarding}{launch_block}
    var presentation: ScreenPresentation {{
        switch self {{
{presentations}
        }}
    }}

    /// Whether the original shows the tab bar on this screen (tab roots and screens
    /// whose app_spec components include a tab bar).
    var showsTabBar: Bool {{
        {bar_check}
    }}

    /// Tab whose navigation stack hosts this screen (nil: onboarding or modal).
    var tab: AppTab? {{
        switch self {{
{owners}
        }}
    }}

    @MainActor @ViewBuilder
    func makeView() -> some View {{
        switch self {{
{views}
        }}
    }}
}}

enum ScreenPresentation {{
    case onboarding, tabRoot, push, sheet, fullScreenCover
}}
{launch_type}"""


def render_app_tab(tabs: list[TabEntry], *, shows_bar: bool) -> str:
    """``AppTab`` enum: root tabs in order, their titles and root screens."""
    cases = "\n".join(
        f"    case {t.case_name} = {swift_str(t.root.screen_id)}  // {clean_text(t.title)}"
        for t in tabs
    )
    titles = "\n".join(f"        case .{t.case_name}: {swift_str(t.title)}" for t in tabs)
    roots = "\n".join(f"        case .{t.case_name}: .{t.root.case_name}" for t in tabs)
    return f"""import SwiftUI

/// Root tabs, left to right; each owns one navigation stack.
/// {DO_NOT_EDIT}
enum AppTab: String, CaseIterable, Identifiable, Hashable {{
{cases}

    var id: String {{ rawValue }}

    static let home: AppTab = .{tabs[0].case_name}

    /// False for apps without a tab bar (single implicit tab).
    static let showsTabBar = {"true" if shows_bar else "false"}

    var title: String {{
        switch self {{
{titles}
        }}
    }}

    var root: ScreenID {{
        switch self {{
{roots}
        }}
    }}
}}
"""


ROUTER = f"""import Observation
import SwiftUI

/// Navigation state. `open(_:)` implements the headless screen-id contract:
/// it selects the owning tab and rebuilds its stack so the requested screen is on
/// top, presents modal targets over the home tab and shows onboarding screens
/// outside the tabs. {DO_NOT_EDIT}
@Observable
final class Router {{
    var selectedTab: AppTab = .home
    var paths: [AppTab: [ScreenID]] = [:]
    var sheet: ScreenID?
    var cover: ScreenID?
    var onboarding: ScreenID?
    var unknownID: String?

    static let onboardingDoneKey = "iosforge.onboarding_done"

    static func launch() -> Router {{
        let router = Router()
        if let raw = Headless.screenID {{
            router.open(raw)
        }} else if !UserDefaults.standard.bool(forKey: onboardingDoneKey),
                  let start = ScreenID.onboardingStart {{
            router.onboarding = start
        }}
        return router
    }}

    func path(for tab: AppTab) -> [ScreenID] {{
        paths[tab] ?? []
    }}

    func setPath(_ path: [ScreenID], for tab: AppTab) {{
        paths[tab] = path
    }}

    func open(_ raw: String) {{
        paths = [:]
        sheet = nil
        cover = nil
        onboarding = nil
        unknownID = nil
        selectedTab = .home
        guard let screen = ScreenID(rawValue: raw) else {{
            unknownID = raw
            return
        }}
        if let tab = screen.tab {{
            selectedTab = tab
        }}
        show(screen)
    }}

    func show(_ screen: ScreenID) {{
        switch screen.presentation {{
        case .onboarding:
            onboarding = screen
        case .tabRoot:
            onboarding = nil
            selectedTab = screen.tab ?? .home
            paths[selectedTab] = []
        case .push:
            onboarding = nil
            paths[selectedTab, default: []].append(screen)
        case .sheet:
            sheet = screen
        case .fullScreenCover:
            cover = screen
        }}
    }}

    func select(_ tab: AppTab) {{
        selectedTab = tab
    }}

    func dismiss() {{
        if cover != nil {{
            cover = nil
        }} else if sheet != nil {{
            sheet = nil
        }} else if !path(for: selectedTab).isEmpty {{
            paths[selectedTab]?.removeLast()
        }}
    }}

    func finishOnboarding() {{
        if !Headless.isActive {{
            UserDefaults.standard.set(true, forKey: Router.onboardingDoneKey)
        }}
        onboarding = nil
        selectedTab = .home
    }}

    func handle(_ url: URL) {{
        guard url.scheme == "iosforge", url.host == "screen",
              let raw = url.pathComponents.dropFirst().first else {{ return }}
        open(raw)
    }}
}}
"""

LAUNCH_TYPE = """
/// A screen the app presents over itself on start, and when.
struct ScaffoldLaunchScreen {
    enum Condition {
        case everyLaunch, firstLaunch, notPremium
    }

    let screen: ScreenID
    let asSheet: Bool
    let condition: Condition
}
"""

LAUNCH_METHOD = """\
    /// Presents the first `ScreenID.launchScreens` entry whose condition holds;
    /// never in headless screen-id mode or over onboarding.
    @MainActor
    func presentLaunch() {
        guard !Headless.isActive, onboarding == nil else { return }
        for entry in ScreenID.launchScreens {
            let key = "iosforge.launch_shown.\\(entry.screen.rawValue)"
            switch entry.condition {
            case .everyLaunch:
                break
            case .firstLaunch:
                if UserDefaults.standard.bool(forKey: key) { continue }
            case .notPremium:
                if Subscriptions.hasPremium { continue }
            }
            UserDefaults.standard.set(true, forKey: key)
            if entry.asSheet {
                sheet = entry.screen
            } else {
                cover = entry.screen
            }
            return
        }
    }

"""


def render_router(*, launch: bool = False) -> str:
    """``Router``; with ``launch`` it also presents the launch screens (after onboarding too)."""
    if not launch:
        return ROUTER
    router = ROUTER.replace(
        "        onboarding = nil\n        selectedTab = .home\n    }\n",
        "        onboarding = nil\n        selectedTab = .home\n"
        "        Task { @MainActor in self.presentLaunch() }\n    }\n",
        1,
    )
    return router.replace(
        "    func handle(_ url: URL) {", LAUNCH_METHOD + "    func handle(_ url: URL) {", 1
    )


ROOT_VIEW = f"""import SwiftUI

/// Hosts onboarding, the tab stacks and modal presentations driven by `Router`.
/// {DO_NOT_EDIT}
struct RootView: View {{
    @Environment(Router.self) private var router

    var body: some View {{
        @Bindable var router = router
        content
            .sheet(item: $router.sheet) {{ $0.makeView() }}
            .fullScreenCover(item: $router.cover) {{ $0.makeView() }}
    }}

    @ViewBuilder
    private var content: some View {{
        if let unknown = router.unknownID {{
            UnknownScreenView(id: unknown)
        }} else if let onboarding = router.onboarding {{
            onboarding.makeView()
        }} else {{
            TabRootView()
        }}
    }}
}}

/// The selected tab's navigation stack plus the app's single tab bar, shown only
/// while the top screen of the stack is one the original shows it on.
struct TabRootView: View {{
    @Environment(Router.self) private var router

    var body: some View {{
        @Bindable var router = router
        let tab = router.selectedTab
        VStack(spacing: 0) {{
            NavigationStack(path: Binding(
                get: {{ router.path(for: tab) }},
                set: {{ router.setPath($0, for: tab) }}
            )) {{
                tab.root.makeView()
                    .navigationDestination(for: ScreenID.self) {{ $0.makeView() }}
            }}
            .id(tab)
            if AppTab.showsTabBar, (router.path(for: tab).last ?? tab.root).showsTabBar {{
                AppTabBar(tabs: AppTab.allCases, selection: $router.selectedTab)
            }}
        }}
    }}
}}

/// Explicit, detectable screen for an unknown `-screen-id` (never a silent fallback).
struct UnknownScreenView: View {{
    let id: String

    var body: some View {{
        VStack(spacing: 12) {{
            Image(systemName: "exclamationmark.triangle.fill")
                .font(.system(size: 48))
            Text("UNKNOWN SCREEN-ID")
                .font(.title2.bold())
            Text(id)
                .font(.body.monospaced())
        }}
        .foregroundStyle(.red)
        .frame(maxWidth: .infinity, maxHeight: .infinity)
        .background(Color.white)
        .accessibilityIdentifier("iosforge.unknown-screen")
    }}
}}

/// Placeholder for a screen the generator has not produced yet.
struct PendingScreenView: View {{
    let id: String

    var body: some View {{
        Text("Screen \\(id) not generated")
            .foregroundStyle(.secondary)
            .frame(maxWidth: .infinity, maxHeight: .infinity)
            .accessibilityIdentifier("iosforge.pending-screen")
    }}
}}
"""

HEADLESS = f"""import Foundation

/// Headless screen-id mode (`-screen-id <id>` launch argument, UserDefaults
/// argument domain). While active: no onboarding, no permission prompts,
/// fixture data only, no capture services. {DO_NOT_EDIT}
enum Headless {{
    static let screenID: String? = UserDefaults.standard.string(forKey: "screen-id")

    static var isActive: Bool {{ screenID != nil }}
}}
"""

MEDIA = f"""import UIKit

/// Bundled media from the source app (`Resources/Media`, folder reference).
/// {DO_NOT_EDIT}
enum MediaAsset {{
    static func url(_ file: String) -> URL? {{
        let parts = file.split(separator: "/").map(String.init)
        let folder = (["Media"] + parts.dropLast()).joined(separator: "/")
        return Bundle.main.url(forResource: parts.last, withExtension: nil, subdirectory: folder)
    }}

    static func image(_ file: String) -> UIImage? {{
        url(file).flatMap {{ UIImage(contentsOfFile: $0.path) }}
    }}
}}
"""

THEME_PLACEHOLDER = """import SwiftUI

/// Design tokens. Replaced by the theme task.
enum Theme {}
"""

FIXTURES_PLACEHOLDER = """import Foundation

/// Fixture data for headless rendering; screens add `extension Fixtures` files.
enum Fixtures {}
"""

TAB_BAR_PLACEHOLDER = """import SwiftUI

/// The app's single tab bar (visual only). Replaced by the component_library task;
/// the signature `AppTabBar(tabs:selection:)` is fixed by the scaffold.
struct AppTabBar: View {
    let tabs: [AppTab]
    @Binding var selection: AppTab

    var body: some View {
        HStack {
            ForEach(tabs) { tab in
                Button(tab.title) { selection = tab }
                    .frame(maxWidth: .infinity)
            }
        }
        .padding(.vertical, 10)
        .background(.bar)
    }
}
"""


def render_permissions() -> str:
    """The permission gate: kinds, prompter protocol and the headless no-op."""
    cases = "\n".join(f"    case {kind.case}" for kind in PERMISSION_KINDS)
    return f"""import Foundation

/// Every system prompt iOS can show. {DO_NOT_EDIT}
enum PermissionKind: String, CaseIterable {{
{cases}
}}

/// One concrete system prompt. Implementations live in `{PERMISSIONS_DIR}/` and are
/// only ever invoked through `Permissions.request(_:)`.
protocol PermissionPrompter {{
    static var kind: PermissionKind {{ get }}
    static func prompt() async -> Bool
}}

/// The single gate for permission prompts: a no-op returning `false` in headless
/// screen-id mode so no system alert can cover the captured screen.
enum Permissions {{
    @discardableResult
    static func request<P: PermissionPrompter>(_ prompter: P.Type) async -> Bool {{
        guard !Headless.isActive else {{ return false }}
        return await prompter.prompt()
    }}
}}
"""


def render_app(target: str, startup: list[str] | None = None, *, launch: bool = False) -> str:
    """``@main`` entry point wiring ``Router`` into ``RootView`` and starting the modules.

    With ``launch`` the entry point presents the launch screens once the modules started.
    """
    calls = (
        startup if startup is not None else ["Subscriptions.start()", "await Attribution.start()"]
    )
    if launch:
        calls = [*calls, "router.presentLaunch()"]
    task = "\n".join(f"                    {call}" for call in calls)
    return f"""import SwiftUI

/// App entry point. {DO_NOT_EDIT}
@main
struct {target}App: App {{
    @State private var router = Router.launch()

    var body: some Scene {{
        WindowGroup {{
            RootView()
                .environment(router)
                .onOpenURL {{ router.handle($0) }}
                .task {{
{task}
                }}
        }}
    }}
}}
"""


def render_pending(entry: ScreenEntry) -> str:
    """Compiling placeholder view until the screen task replaces it."""
    return f"""import SwiftUI

/// {clean_text(entry.name)} — placeholder until the screen task generates it.
struct {entry.type_name}: View {{
    var body: some View {{
        {PENDING_MARKER} {swift_str(entry.screen_id)})
    }}
}}
"""
