"""Inline prompts for the SwiftUI codegen (theme, screen, compile fix).

Prompts stay inline (accepted SPEC §6 tech-debt, DECISIONS 2026-10-09 Phase 3).
They only ever ask the model to fill the scaffold's extension points; the
navigation, headless mode and permission gate are rendered by
:mod:`iosforge.mvp.swiftui_scaffold` and must not be touched. The workspace
carries ``reference/`` (``docs/swiftui-reference``) as the worked example.
"""

from __future__ import annotations

from iosforge.mvp.swiftui_permissions import PERMISSION_KINDS, PERMISSIONS_DIR
from iosforge.mvp.swiftui_scaffold import ScreenEntry

APP_DIR = "xcode_app"

_SCAFFOLD_FILES = (
    "project.yml",
    "App/App.swift",
    "App/Navigation/*",
    "App/Headless/*",
    f"{PERMISSIONS_DIR}/Permissions.swift",
    "App/Support/MediaAsset.swift",
)

_PROMPTING_APIS = ", ".join(sorted({kind.case for kind in PERMISSION_KINDS}))

BASE_RULES = f"""You are generating part of a native iOS app in SwiftUI. The Xcode project
lives in `{APP_DIR}/` and is generated with XcodeGen by IOSForge.

HARD RULES
- iOS 17+, SwiftUI, Swift 5 language mode, Observation allowed. Apple frameworks only:
  no Swift packages, no CocoaPods, no UIKit view controllers (UIKit types like UIImage are fine).
- NEVER edit scaffold files (header "Generated by the IOSForge scaffold — do not edit"):
  {", ".join(f"`{APP_DIR}/{f}`" for f in _SCAFFOLD_FILES)}. Never create or edit an
  `.xcodeproj`, never run xcodegen/xcodebuild — IOSForge builds and checks the project.
- Navigation only through the scaffold Router: `@Environment(Router.self) private var router`,
  then `router.show(.<case>)` for a `ScreenID` case that EXISTS in
  `{APP_DIR}/App/Navigation/ScreenID.swift`, and `router.dismiss()` to go back. No
  NavigationStack, NavigationLink(destination:) or .sheet of your own inside screens.
- Headless screen-id mode (`Headless.isActive`): the app is launched straight onto one screen
  for a screenshot. Every screen MUST render completely on first frame from `Fixtures` data,
  with no user interaction, no network, no auto-navigation and no timers firing navigation.
- System permission prompts ({_PROMPTING_APIS}) are FORBIDDEN outside
  `{APP_DIR}/{PERMISSIONS_DIR}/`. To ask for one, add
  `{APP_DIR}/{PERMISSIONS_DIR}/<Kind>Permission.swift` with
  `enum <Kind>Permission: PermissionPrompter {{ static let kind: PermissionKind = .<case>;
  static func prompt() async -> Bool {{ ... }} }}` and call
  `await Permissions.request(<Kind>Permission.self)` from a user action. Never call
  `.prompt()` directly. The gate is a no-op in headless mode.
- Bundled fonts: `Font.custom("<postscript_name>", size:)` with names from `fonts.json`
  (files with `is_system: false`); system fonts otherwise. Bundled media:
  `MediaAsset.image("<file>")` / `MediaAsset.url("<file>")` where `<file>` is the file name of
  a `media.json` entry's `path` (without the `media/` prefix).
- No ads: never add ad SDKs or ad placeholders; collapse the space ads used to take.
- `reference/` holds a minimal working example of this architecture (read-only).
- Code without inline `//` comments; short `///` doc comments on types are fine.
"""

DIVERGENCE_NOTE = """CONTENT DIVERGENCE: keep the structure and layout of the original, but
paraphrase every user-visible string, use SF Symbols instead of copying the original's
icons, and never use the original app's name, logo or branding.
"""


def theme_prompt(*, app_name: str, diverge_content: bool = True) -> str:
    """Theme task: design tokens → ``App/Theme/`` Swift (colours, fonts, styles)."""
    return f"""{BASE_RULES}
{DIVERGENCE_NOTE if diverge_content else ""}
TASK: theme for "{app_name}".
Read `app_spec.json` → `design_tokens` (W3C tokens: color, font, dimension, gradient,
button_style, elevation_style, dark_mode, ios_adaptation) and `fonts.json`. Replace
`{APP_DIR}/App/Theme/Theme.swift` (you may add more files under `{APP_DIR}/App/Theme/`) with:
- `extension Color` palette from the colour tokens (hex initialiser included in your files);
- `enum AppFont` helpers mapping heading/body/etc. tokens to bundled fonts by postscript name;
- spacing / corner-radius constants from dimension tokens;
- `LinearGradient` values from gradient tokens;
- `ButtonStyle`s from `button_style` and shadow modifiers from `elevation_style`.
Keep a type named `Theme` (it may become a namespace enum). Write ONLY under
`{APP_DIR}/App/Theme/`. The project must compile.
"""


def screen_prompt(
    entry: ScreenEntry,
    *,
    targets: list[ScreenEntry],
    diverge_content: bool = True,
) -> str:
    """Screen task: one ``app_spec`` screen → its view, fixtures and optional prompters."""
    if targets:
        nav = "\n".join(f"  - `.{t.case_name}` — {t.name} ({t.presentation})" for t in targets)
        nav_block = f"Navigation targets available from this screen (use router.show):\n{nav}"
    else:
        nav_block = (
            "No other screen exists in this build yet: controls that would navigate elsewhere "
            "render normally but their action is a no-op."
        )
    suffix = entry.type_name.removeprefix("Screen").removesuffix("View")
    return f"""{BASE_RULES}
{DIVERGENCE_NOTE if diverge_content else ""}
TASK: implement screen `{entry.screen_id}` — "{entry.name}" (presentation: {entry.presentation}).

INPUTS (ground truth, read them all):
- `app_spec.json` → the `screens[]` entry with id `{entry.screen_id}`: components, layout_notes,
  states (render the "default" state), dynamic_content.
- `screens/{entry.screen_id}.png` — screenshot of the original screen. Match its layout,
  hierarchy, proportions, colours and typography closely.
- `source/{entry.screen_id}.json` — the original native view tree (frames in points,
  `screen_size`, fonts, colours, `asset_ref.media_id`). Use it for exact geometry, spacing and
  font sizes; skip ad containers.
- `media.json` / `fonts.json` — bundled assets you may use.
- The theme in `{APP_DIR}/App/Theme/` — use its colours, fonts and styles.

OUTPUT:
- Replace `{APP_DIR}/{entry.view_path}` with the real screen. Keep `struct {entry.type_name}: View`
  with no initialiser parameters. Sub-views may go in extra files under
  `{APP_DIR}/App/Features/{entry.screen_id}/`.
- Put the data the screen shows in `{APP_DIR}/App/Fixtures/Fixtures{suffix}.swift` as
  `extension Fixtures {{ ... }}` and read it from the view (realistic values, not lorem ipsum).
- If the screen shows a tab bar, draw it as part of this screen for now (selected tab per the
  screenshot); tabs whose screen is not listed below are no-ops.
- {nav_block}
"""


def compile_fix_prompt(errors: list[str]) -> str:
    """Compile-gate fix task for the given xcodebuild / permission-lint errors."""
    listed = "\n".join(errors)
    return f"""{BASE_RULES}
TASK: the project in `{APP_DIR}/` does not build. Below are the errors from xcodebuild and
from the IOSForge permission lint. Fix ONLY these errors with the smallest edits: imports,
types, missing members, typos. Permission-lint errors mean a system prompt API is used outside
`{APP_DIR}/{PERMISSIONS_DIR}/`: move it into a PermissionPrompter there and call
`Permissions.request(...)`. Do NOT change layout, colours, fonts or navigation, and never edit
scaffold files.

errors:
{listed}
"""
