"""baseline schema

Revision ID: 6522a3910bc0
Revises:
Create Date: 2026-06-22 12:01:17.363650

"""
# ruff: noqa: E501  (autogenerated migration: long op.* lines are kept verbatim)
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6522a3910bc0'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor', sa.String(length=256), nullable=False),
    sa.Column('action', sa.String(length=256), nullable=False),
    sa.Column('object_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_table('prompt_sets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('purpose', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_sets')),
    sa.UniqueConstraint('name', name='prompt_set_name')
    )
    op.create_table('provider_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider_type', sa.String(length=128), nullable=False),
    sa.Column('active_implementation', sa.String(length=128), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_configs')),
    sa.UniqueConstraint('provider_type', name='provider_type_unique')
    )
    op.create_table('source_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('resources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_configs'))
    )
    op.create_index(op.f('ix_source_configs_source_type'), 'source_configs', ['source_type'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('prompt_set_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prompt_set_id'], ['prompt_sets.id'], name=op.f('fk_prompt_versions_prompt_set_id_prompt_sets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_versions')),
    sa.UniqueConstraint('prompt_set_id', 'version', name='prompt_version_seq')
    )
    op.create_index(op.f('ix_prompt_versions_prompt_set_id'), 'prompt_versions', ['prompt_set_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_app_ref', sa.String(length=512), nullable=False),
    sa.Column('source_app_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state', sa.Enum('QUEUED', 'DISCOVERY', 'ACQUISITION', 'WALKTHROUGH', 'ANALYSIS', 'CODEGEN', 'DELIVERY', 'DONE', 'NEEDS_INPUT', 'RETRYABLE', 'FAILED', 'CANCELLED', name='job_state'), nullable=False),
    sa.Column('emulator_provider', sa.String(length=128), nullable=True),
    sa.Column('catalog_provider', sa.String(length=128), nullable=True),
    sa.Column('apk_source_provider', sa.String(length=128), nullable=True),
    sa.Column('codegen_target', sa.String(length=128), nullable=True),
    sa.Column('prompt_version_id', sa.Uuid(), nullable=True),
    sa.Column('result_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_versions.id'], name=op.f('fk_jobs_prompt_version_id_prompt_versions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_table('apk_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('version', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=256), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_apk_artifacts_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_apk_artifacts'))
    )
    op.create_index(op.f('ix_apk_artifacts_job_id'), 'apk_artifacts', ['job_id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('package_id', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('publisher', sa.String(length=512), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_candidates_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidates'))
    )
    op.create_index(op.f('ix_candidates_job_id'), 'candidates', ['job_id'], unique=False)
    op.create_table('generation_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('sources_key', sa.String(length=1024), nullable=False),
    sa.Column('compliance_score', sa.Float(), nullable=True),
    sa.Column('selftest_report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prompt_version_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_generation_results_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_versions.id'], name=op.f('fk_generation_results_prompt_version_id_prompt_versions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation_results'))
    )
    op.create_index(op.f('ix_generation_results_job_id'), 'generation_results', ['job_id'], unique=False)
    op.create_table('stage_timeline',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.Enum('DISCOVERY', 'ACQUISITION', 'WALKTHROUGH', 'ANALYSIS', 'CODEGEN', 'DELIVERY', name='pipeline_stage'), nullable=False),
    sa.Column('input_hash', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_stage_timeline_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stage_timeline')),
    sa.UniqueConstraint('job_id', 'stage', 'input_hash', name='stage_idempotency')
    )
    op.create_index(op.f('ix_stage_timeline_job_id'), 'stage_timeline', ['job_id'], unique=False)
    op.create_table('walkthrough_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('screenshot_keys', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('screen_map', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=128), nullable=True),
    sa.Column('strategy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_walkthrough_results_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_walkthrough_results'))
    )
    op.create_index(op.f('ix_walkthrough_results_job_id'), 'walkthrough_results', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_walkthrough_results_job_id'), table_name='walkthrough_results')
    op.drop_table('walkthrough_results')
    op.drop_index(op.f('ix_stage_timeline_job_id'), table_name='stage_timeline')
    op.drop_table('stage_timeline')
    op.drop_index(op.f('ix_generation_results_job_id'), table_name='generation_results')
    op.drop_table('generation_results')
    op.drop_index(op.f('ix_candidates_job_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_apk_artifacts_job_id'), table_name='apk_artifacts')
    op.drop_table('apk_artifacts')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_prompt_versions_prompt_set_id'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index(op.f('ix_source_configs_source_type'), table_name='source_configs')
    op.drop_table('source_configs')
    op.drop_table('provider_configs')
    op.drop_table('prompt_sets')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
    # Native PostgreSQL enum types are not auto-dropped by autogenerate.
    bind = op.get_bind()
    sa.Enum(name='job_state').drop(bind, checkfirst=True)
    sa.Enum(name='pipeline_stage').drop(bind, checkfirst=True)
