"""admin_users + job manual-upload columns

Revision ID: c71df70acc3b
Revises: 6522a3910bc0
Create Date: 2026-06-22 13:38:27.954139

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c71df70acc3b"
down_revision: str | Sequence[str] | None = "6522a3910bc0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=128), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_users")),
        sa.UniqueConstraint("username", name="admin_user_username"),
    )
    op.add_column("jobs", sa.Column("created_by_id", sa.Uuid(), nullable=True))
    op.add_column(
        "jobs",
        sa.Column(
            "submission_kind",
            sa.String(length=32),
            nullable=False,
            server_default="manual_apk",
        ),
    )
    op.create_foreign_key(
        op.f("fk_jobs_created_by_id_admin_users"),
        "jobs",
        "admin_users",
        ["created_by_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_jobs_created_by_id_admin_users"), "jobs", type_="foreignkey")
    op.drop_column("jobs", "submission_kind")
    op.drop_column("jobs", "created_by_id")
    op.drop_table("admin_users")
    # ### end Alembic commands ###
